name: test_project_flutter
description: A test Flutter project for Broxus.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  flutter_staggered_grid_view: ^0.4.1
  dio: ^4.0.4
  http: ^0.13.4
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  equatable: ^2.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true


